### ISSUE TITLE
Odd number of students.

### ISSUE THREAD

**Issue by Dmfama20** [kulmann/moodle-mod_challenge#23]
Hi,
I've recognized the following issue:

- add three students to the course,
-  create a game round of 60 minutes, containing 60 duels,
- start the first duel -> one student is not matched,
- the non-matched student is marked with an hourglass (=waiting for the student),
- if the non-machted student logs into the course and starts the activity, he sees the notification that the game has not been started
=> No ongoing game is possible and duel number 2 won't start.

The same setting, but 2 instead of 3 students, works without problem and all duels can be made.

---------
Following issue was split out into https://github.com/kulmann/moodle-mod_challenge/issues/24 by @kulmann 
---------
One other small thing: when creating a duel, the time is not the chosen time, but the current time (if chosen time is before current time) .

**Comment by kulmann** [comment]
Hey @Dmfama20, thanks for reporting this. I'll split the issue into two issues two be able to solve them independently -> will split out the smaller issue from your description and edit this issue description accordingly.

Can you think of a good solution for the odd number of students? A naive approach would be to match one student twice. That doesn't seem to be fair either... to be honest I'm a bit puzzled by this. 😅

**Comment by Dmfama20** [comment]
Hey,
maybe the easiest way is to ask the questions to the remaining person (duel with only one person). Afterwards, the person will earn the respective points if he has at least 50% of the total points. 
What do you think?

**Comment by Dmfama20** [comment]
Hey @kulmann 
are there any news about this issue?
